name: PR Checks

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  call-commit-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Needed so we can check a range of commits
          fetch-depth: 0
      - uses: ./actions/check_commit_messages/

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python ./hooks/commit_message_checker/tests/test_commit_checker.py
        shell: bash
